# Generated by Django 4.1.3 on 2022-11-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='apellido',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='directores',
            name='nombre',
            field=models.CharField(help_text='Coloca el nombre del director', max_length=64),
        ),
    ]
