# Generated by Django 4.1.3 on 2022-11-18 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0002_directores_apellido_alter_directores_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='fallecimiento',
            field=models.DateField(help_text='Si sigue vivo dejar en blanco', null=True),
        ),
        migrations.AddField(
            model_name='directores',
            name='nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
