# Generated by Django 4.1.3 on 2022-11-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0004_alter_directores_fallecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('pais', models.CharField(max_length=64)),
                ('duracion', models.PositiveIntegerField()),
                ('genero', models.CharField(blank=True, choices=[('c', 'Comedia'), ('f', 'Ciencia Ficción'), ('d', 'drama'), ('t', 'Terror')], max_length=1)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='directores',
            name='biografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='directores',
            name='pais',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='directores',
            name='pelis',
            field=models.ManyToManyField(to='directores.peliculas'),
        ),
    ]
