# Generated by Django 4.1.3 on 2022-11-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0005_peliculas_directores_biografia_directores_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='foto',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='poster',
            field=models.URLField(null=True),
        ),
    ]
