# Generated by Django 4.1.3 on 2022-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0006_directores_foto_peliculas_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directores',
            name='pelis',
            field=models.ManyToManyField(blank=True, to='directores.peliculas'),
        ),
    ]
