# Generated by Django 4.1.3 on 2022-11-24 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0007_alter_directores_foto_alter_directores_pelis'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
