# Generated by Django 4.1.3 on 2022-11-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0008_directores_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directores',
            name='picture',
        ),
    ]
