# Generated by Django 4.1.3 on 2022-11-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0009_remove_directores_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directores',
            name='pelis',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directores.directores'),
        ),
    ]
