# Generated by Django 4.1.3 on 2022-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0010_remove_directores_pelis_peliculas_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Poner la duración en minutos'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
