# Generated by Django 4.1.3 on 2022-11-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0011_alter_peliculas_duracion_alter_peliculas_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='foto',
            field=models.URLField(blank=True, help_text='Coloque la dirección URL de la foto', null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='poster',
            field=models.URLField(blank=True, help_text='Coloque la dirección URL de la foto', null=True),
        ),
    ]
